name: NodeJS with Gulp

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Build
      run: |
        npm install
        gulp bundle

    - name: upload bundle
      uses: actions/upload-artifact@v4
      with:
        name: ui-bundle
        path: build/ui-bundle.zip
